강아지 추가/수정 시 썸네일 이미지를 기본 이미지로 변경할 수 있도록 수정
nbc-final-team2/ddaraogae pull request #158
Opened 2024-06-18 05:14 UTC by neoneoneo123

resolved: #150 

---

- 강아지 추가 시
  - 정보를 입력하는 과정에서 이미지를 선택했다가 지울 수 있도록 수정하였습니다.
    - 즉, 처음 열였을 때처럼 기본 이미지로 다시 설정하는 기능이 추가된 것
- 강아지 수정 시
  - 썸네일 이미지만 삭제할 수 있습니다.
  - 강아지 추가 시와 동일하게 정보를 입력하는 과정에서 이미지를 선택했다가 지울 수 있도록 수정하엿습니다.
  - 기존에 썸네일 이미지가 있는 강아지 정보에서 썸네일 이미지 삭제 후 저장 시 storage에서 해당 강아지의 썸네일 이미지를 제거합니다.
  - 썸네일 이미지 삭제 시 기본 썸네일 이미지로 표시됩니다(서버에는 기본  썸네일 이미지가 올라가지 않습니다).
    - 기본 썸네일 이미지는 저희 앱에서 사용하는 발바닥 이미지로 변경하였습니다.

2024-06-18 06:08 UTC, theBettor requested changes
![스크린샷 2024-06-18 오후 3 06 58](https://github.com/nbc-final-team2/ddaraogae/assets/89888486/b5588897-a0c3-438f-8984-189042f19588)

![스크린샷 2024-06-18 오후 3 07 18](https://github.com/nbc-final-team2/ddaraogae/assets/89888486/627851bb-2aea-4098-a3bb-5bd4d0e558d6)
강아지 추가할때 완료 버튼을 빠르게 두번 누르면 강아지 2마리가 생성됩니다! 이 문제만 해결되면 좋을 것 같고, 추가적으로 강아지를 삭제하고자 할때 '정말 삭제하시겠습니까'라는 메시를 다이어로그로 띄워주면 좋을듯합니다!

2024-06-18 07:50 UTC, neoneoneo123 commented
@theBettor

https://github.com/nbc-final-team2/ddaraogae/issues/159
https://github.com/nbc-final-team2/ddaraogae/issues/160

이슈 추가해놓았습니다.
별도로 브랜치를 작업하는 것보다는 이번 브랜치에서 해결하려고 합니다.

2024-06-18 08:03 UTC, theBettor approved these changes

2024-06-18 08:04 UTC, theBettor commented
> @theBettor
> 
> #159 #160
> 
> 이슈와 마일스톤에 해당 작업 추가해놓았습니다. 별도로 브랜치를 작업하는 것보다는 이번 브랜치에서 해결하려고 합니다.

최곱니다 approve로 바꿨어용

2024-06-18 08:52 UTC, neoneoneo123 commented
@theBettor 님 말씀 주신 작업 완료하여 push 해두었습니다!

https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/040aa8a97e6fa6640acdb18181109c0317d22ec9
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/0dbcaeeefd1f6bc341b9048d9645331e8f52d41a
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/042c41991aead77ed41ba5cfc597dac29a5a6c48

2024-06-18 08:53 UTC, winteryy requested changes
몇 군데 버그가 있는 것 같아서 코멘트 남겼습니다!

2024-06-18 08:53 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +            }
View의 visible 상태와는 무관하게 위젯 객체는 계속 존재하는 것으로 알고 있습니다
바뀌는 값에 의해 새로운 리스너를 달 필요가 있지 않다면 View 초기화 이후 한번만 달아줘도 무방할 것 같습니다

2024-06-18 08:53 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +            activeRemoveThumbnail(result.data?.data)
이렇게 되면 이미지를 가져오는 런처의 결과에 의해서만 View처리가 발생하고, 해당 상태 또한 저장되지 않는 위험이 있습니다(아래와 같은 상황이 발생합니다)
이미지 uri가 정상적으로 가져와진다면 ViewModel 내의 State에 항상 반영되니까 그걸 이용해볼 수 있을 것 같습니다

[Screen_recording_20240618_173811.webm](https://github.com/nbc-final-team2/ddaraogae/assets/104819764/88cafc4d-88bc-43bc-82e1-ba38dd094308)

2024-06-18 08:53 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +        }
삭제 방지턱을 주는 건 좋은 UX 같습니다!

2024-06-18 08:53 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +                intent.putExtra(DOGDATA, it)
상수로 대체한 부분도 좋습니다👍

2024-06-18 08:53 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +            } else {
받은 이미지는 없지만 기존에 가지고 있던 이미지가 있는지 고려하는 흐름은 작성되지 않은 것 같습니다
구현에 따라 좀 다르겠지만, 저였으면 이 곳에서 처리했을 것 같아 이 곳에 코멘트 남깁니다

발생하는 문제는 아래와 같습니다

[Screen_recording_20240618_175145.webm](https://github.com/nbc-final-team2/ddaraogae/assets/104819764/a2f4b650-be1a-4e34-8634-2de550069682)

2024-06-18 08:53 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +            activeRemoveThumbnail()
`AddActivity`에서의 코멘트와 같습니다

2024-06-18 11:57 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +            }
수정하였습니다!

최종적으로 fix된 commit의 링크입니다.
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/490ec3144a025f7b9201b3f0f75fc47052445b53

2024-06-18 11:57 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +            activeRemoveThumbnail(result.data?.data)
수정하였습니다!

최종적으로 fix된 commit의 링크입니다.
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/490ec3144a025f7b9201b3f0f75fc47052445b53

2024-06-18 11:58 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +            } else {
수정하였습니다!

최종적으로 fix된 commit의 링크입니다.
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/490ec3144a025f7b9201b3f0f75fc47052445b53

2024-06-18 11:58 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +            activeRemoveThumbnail()
수정하였습니다!

최종적으로 fix된 commit의 링크입니다.
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/490ec3144a025f7b9201b3f0f75fc47052445b53

2024-06-18 15:14 UTC, juseonghyun approved these changes
기능 정상 작동하는것 확인했습니다!
수고하셨습니다!

2024-06-19 03:48 UTC, winteryy requested changes
몇몇 부분 확인해서 코멘트 남겼습니다!!

2024-06-19 03:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +                ivDogThumbnail.setImageResource(R.drawable.ic_dog_default_thumbnail)
AddActivity에서 코멘트 드린 것과 같은 방식으로 바꿀 수 있을 것 같습니다

2024-06-19 03:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +                ivRemoveThumbnail.visibility = View.GONE
이 코드랑 176번째줄 `if (state.isThumbnailVisible || dogData?.thumbnailUrl != null)`를 보니까 왜 이렇게 구현하게 됐는지 알 것 같네요
Zep에서 따로 한번 말씀 드리겠습니다

2024-06-19 03:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +            val updateDogDto = if (byteImage != null) {
Zep에서 함께 설명 드린 것 같아 이쪽 코멘트는 생략하겠습니다!

2024-06-19 05:14 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +                ivRemoveThumbnail.visibility = View.GONE
희광님, 말씀 주신 사항들 적용해보았습니다!

최대한 이해한만큼 적용했는데.. 개선 필요한 부분이 있으면 편히 말씀 바랍니다!
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/d451e6777074b303dc7fa1572f38e1fdfe4a5476

2024-06-19 05:14 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +            val updateDogDto = if (byteImage != null) {
https://github.com/nbc-final-team2/ddaraogae/pull/158#discussion_r1645351784 코멘트에 대한 답변과 동일합니다.

2024-06-19 05:22 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +                ivDogThumbnail.setImageResource(R.drawable.ic_dog_default_thumbnail)
https://github.com/nbc-final-team2/ddaraogae/pull/158#discussion_r1645351784 코멘트에 대한 답변과 동일합니다.

2024-06-19 05:23 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +                ivDogThumbnail.setImageResource(R.drawable.ic_dog_default_thumbnail)
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/9a46d330d1c7dce5940e3fd7179604970e817369

수정하였습니다!

2024-06-19 05:23 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddPetViewModel.kt
> +            isThumbnailVisible = imageUri != null || byteArray != null
https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/4bc3a99141c76e737ce3f0d27edcbc60a3951f48

수정하였습니다!

2024-06-19 07:34 UTC, winteryy requested changes
아까 확인 못 한 부분이 하나 있었네요..😂

2024-06-19 07:34 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
>              else rbMale.isChecked = true
기존 이미지 삭제 후, 화면 회전 시 자꾸 기존 이미지가 뜨길래 뭔가 했더니
`initView()`가 `onCreate()`때마다 불리면서 intent로부터 받아온 데이터로 계속 초기화가 되고 있었네요
아까 제가 고려하지 못했던 부분인 것 같습니다😂

EditUiState에 isInit 과 같은 초기화 감지용 프로퍼티를 생성하고
해당 프로퍼티가 false일 때만 이 블럭이 동작하게 해야 할 것 같습니다
viewModel에서 이미지 설정하는 메소드가 불릴 때 해당 프로퍼티가 true로 들어가게 했더니
의도한 대로 동작합니다

2024-06-19 08:05 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
>              else rbMale.isChecked = true
으아

죄송합니다. 제가 그런 상황들을 계속 놓치네요 ㅠ
말씀 주신대로 isInit 변수를 사용하여 화면 회전 시 기존 이미지로 되돌아(?) 가서 보이지 않도록 수정했습니다.

https://github.com/nbc-final-team2/ddaraogae/pull/158/commits/88555ef4f163c62d1a813d19ab272648d5cd56ce

2024-06-19 08:28 UTC, winteryy approved these changes
이젠 다 된 것 같습니다!!
고생 많으셨습니다👍

2024-06-19 08:29 UTC, merged