맵 내 현재 위치 버튼 줌 인/아웃에 맞추기
nbc-final-team2/ddaraogae pull request #204
Opened 2024-06-21 15:27 UTC by theBettor

resolved: #203 

일단 좋은 방법이 없는것 같아서 왼쪽으로 위치를 바꿨는데 어떤가요? 별로거나 다른 방법이 있으면 close하겠습니다.

2024-06-24 10:52 UTC, juseonghyun requested changes
Naver logo 위 ( 왼쪽아래 )가 나을것같습니다!
지금은 먼가 너무 둥 떠있는 느낌..?

2024-06-25 07:00 UTC, winteryy approved these changes
왼쪽 여백이 너무 넓은 느낌은 있네요
줌 인/아웃 버튼 여백이 훨씬 좁아서 그렇게 느껴지는 것 같습니다

2024-06-25 10:45 UTC, neoneoneo123 requested changes
![image](https://github.com/nbc-final-team2/ddaraogae/assets/128209823/954024e0-fcfa-4908-ba9a-3739bad4aa1c)


산책하기를 누르면 버튼이 하단 중앙쯤? 으로 오고 있습니다..!
처음에 위치한 곳에 고정되어야 할 것 같아요!


그리고 우측 중앙에 있는 줌인/아웃 버튼을 조금 더 아래로 내릴 수 있을까요? 기존 현재 위치 버튼이 있는 위치정도로..!

2024-06-25 11:11 UTC, juseonghyun commented
> > Naver logo 위 ( 왼쪽아래 )가 나을것같습니다! 지금은 먼가 너무 둥 떠있는 느낌..?
> 
> ![스크린샷 2024-06-25 오후 8 02 25](https://private-user-images.githubusercontent.com/89888486/342700368-66fb53ab-55c3-4457-99b5-5606781ba548.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTQwMzYsIm5iZiI6MTcxOTMxMzczNiwicGF0aCI6Ii84OTg4ODQ4Ni8zNDI3MDAzNjgtNjZmYjUzYWItNTVjMy00NDU3LTk5YjUtNTYwNjc4MWJhNTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDExMDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZDUwY2QxNTQ1N2ZiMmMzODA3NTY4OGI1ZWMzM2Q1ZmUwN2Y4NmU1ZGU3MTM0OGY1M2U4M2U1NGQyYjY4N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhbhnXdUQ6mq-4Ihl0SnbiwBW-gscC_xaqpbABWTkE8) 이 ![스크린샷 2024-06-25 오후 8 02 35](https://private-user-images.githubusercontent.com/89888486/342700379-f7976d76-3b78-473c-8c66-3b881d7844e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTQwMzYsIm5iZiI6MTcxOTMxMzczNiwicGF0aCI6Ii84OTg4ODQ4Ni8zNDI3MDAzNzktZjc5NzZkNzYtM2I3OC00NzNjLThjNjYtM2I4ODFkNzg0NGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDExMDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNDk1NWEzMjM1ZGUyNGY2MGNiMjYwNGVhMTgzZDM2ZmI1MDdiNGZhNGZhY2U0YTU1YWIxMDVjYjg1MGQ3YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1nkLHG6uQj8ymKaHg2YPTBlejKSXhwMnqT-z8n0Ia9o) 이정도는 어떠신가요?

사실 저의 미적 감각은 전부 reject(?) ㅋㅋ 당했기 때문에 다른분들 생각에 괜찮다면 상관없을 것같습니다.
전보다 훨씬 낫다고 생각합니다!

2024-06-25 11:11 UTC, juseonghyun approved these changes

2024-06-25 11:44 UTC, neoneoneo123 approved these changes
확인했습니다! 👍

2024-06-25 11:46 UTC, merged