[refactor]login 단일 activity로 변경
nbc-final-team2/ddaraogae pull request #227
Opened 2024-06-25 10:07 UTC by JYeyun

로그인 회원가입 페이지 activity -> fragment  변경

2024-06-26 01:38 UTC, theBettor requested changes
![스크린샷 2024-06-26 오전 10 38 28](https://github.com/nbc-final-team2/ddaraogae/assets/89888486/54a7ea16-0f90-488f-871c-a8baae646fe5)
저만 이런 에러가 뜨나요??

2024-06-26 10:02 UTC, JYeyun commented
4005714af2284f13220d31d0f1bbb14baf564476
해당 에러 해결했습니다!

2024-06-26 10:46 UTC, neoneoneo123 reviewed
제 PC에서만 그런건지... 컴퓨터를 껐다가 키고, 캐시도 지워보고, 클린 프로젝트도 해봤지만..

앱을 실행하면 로그인 화면으로 넘어가질 않네요 ㅠ ㅠ

로그창에 에러도 안잡히는 것 같고.. 혹시 관련하여 아시는 부분이 있을까요?

2024-06-26 10:52 UTC, theBettor approved these changes
두고두고 써먹을 수 있는 해결 방법 같네요! 
액티비티 2개를 썻는데 1개로 줄이면서 manifest에서 빼고, 액티비티 위에서 2개의 프래그먼트를 보여주는걸로 이해하는게 맞겠죠?!

2024-06-26 10:54 UTC, theBettor commented
어허라 같은 현상이... 저도 몇번 하니까 넘어가지던데 어쩌다 한번 넘어가지는걸까요...

2024-06-28 01:00 UTC, neoneoneo123 approved these changes
fix 하신 이후로 스플래시 화면에서 잘 넘어갑니다!

근데 LoginActivity에서 사용하지 않는 변수들 viewModel, splachScreen은 일부러 남겨두신 건가요?

2024-06-28 05:05 UTC, JYeyun commented
넵 splashScreen을 선언하지 않으면 스플래쉬 화면 에러가 나서 남겨 두었고 viewModel은 급한 작업 끝난 후 자동 로그인 리펙토링을 하려고 남겨두었습니다!

2024-06-28 05:05 UTC, merged