최근 산책 몇 시간 전인지 UI 제공: 김찬교
nbc-final-team2/ddaraogae pull request #241
Opened 2024-06-26 10:19 UTC by theBettor

resolved: #221 

이슈 참고해주세용.
질문도 있어서 봐주시면 좋습니다.

2024-06-27 15:22 UTC, JYeyun approved these changes
확인 했습니다.
산책을 하자마자 확인할 시 0시간 전이라고 나오는데 '금방 산책을 다녀왔어요' 같은 멘트를 적용해 보는 것도 좋을 것 같습니다.
이슈에 적어주셨던 질문은 구현 상의 문제인지 ui 표현의 문제인지 헷갈려서 말씀 주시면 같이 고민해 보겠습니다!

2024-06-28 01:30 UTC, neoneoneo123 requested changes
고생하셨습니다.

몇 가지 코멘트를 드립니다!

2024-06-28 01:30 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
> +            return "최근에 산책한 기록이 없어요!" // 시간에 대한 정보가 없을때는 아무것도 보여주지 않기 위함.
이런 텍스트는 strings에서 관리되면 좋을 것 같습니다.

2024-06-28 01:30 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
> +                "$hours 시간 전"
strings.xml에 보면

<string name="home_before_time">몇시간전</string>

이게 있는데, 활용하는 곳이 없는 것 같습니다.

여기서 home_before_time를 활용하시면 좋을 것 같습니다.

2024-06-28 01:30 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
> +        Log.d("hours", hours.toString())
시간 숫자인 것 같은데, 별도로 로그를 남겨둔 이유가 있을까요?

2024-06-28 01:30 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
> +        }
24시간 전에 산책한 이력이 없을 때 빈칸으로 두는 것 보다는 "하루 이내 산책 이력이 없어요" 등 뭔가 다른 텍스트를 보여주면 더 좋을 것 같습니다.

2024-06-28 03:37 UTC, theBettor commented
멘트 적용해 보았고, issue에 지연님이 코멘트 달아주셨었는데, 말씀대로 이름을 또 보여줘야 하나 싶더라구요 목적은 '강아지 이름에 맞게 마지막 산책시간을 어떻게 해야 더 직관적으로 보여줄 수 있을까?' 였는데 더 좋은 아이디어는 생각이 안나서 일단은 이렇게 진행하면 될 것 같아요!

2024-06-28 03:37 UTC, theBettor commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
> +            return "최근에 산책한 기록이 없어요!" // 시간에 대한 정보가 없을때는 아무것도 보여주지 않기 위함.
적용 완료 감사합니다!

2024-06-28 03:37 UTC, theBettor commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/util/DateFormatter.kt
> +                "$hours 시간 전"
적용 완료 감사합니다!

2024-06-28 06:26 UTC, neoneoneo123 approved these changes
확인했습니다.

2024-06-28 06:37 UTC, merged