다크 테마 대응
nbc-final-team2/ddaraogae pull request #243
Opened 2024-06-27 08:54 UTC by neoneoneo123

resolved: #209

2024-06-27 15:31 UTC, JYeyun requested changes
다크모드 상태가 되면 글씨가 회색이 되는 것 같습니다.
로그인, 회원가입 창 바탕이 흰색이라 글 입력 시 잘 안보이는 문제가 있습니다.
개인적으로 글씨가 조금 더 밝아도 될 것 같다는 생각이 듭니다.

![image](https://github.com/nbc-final-team2/ddaraogae/assets/117142316/83c9c6aa-e0bb-4b1a-96cf-d95523ec2626)

![image](https://github.com/nbc-final-team2/ddaraogae/assets/117142316/3db0b675-9a7b-450d-b09f-6ccef5cfee0e)

2024-06-28 01:35 UTC, neoneoneo123 commented
@JYeyun

1. 네 다크모드에서는 자동으로 좀 못생긴 회색으로 바뀌기는 합니다. 아예 다 text를 흰색으로 바꾸는 게 좋을까요?
2. edit text view에서는 다크모드일 때 텍스트 색상이 검정색이 되도록 바꾸겠습니다.

2024-06-28 01:39 UTC, JYeyun approved these changes

2024-06-28 01:39 UTC, JYeyun commented
확인했습니다! text 다 흰색으로 바꿔도 좋을 것 같습니다!

2024-07-01 07:26 UTC, juseonghyun approved these changes
테마가 잘 적용된것 확인했습니다!
저는 이상 없다고 생각합니다.
수고하셨습니다!

2024-07-05 01:43 UTC, winteryy approved these changes
![image](https://github.com/nbc-final-team2/ddaraogae/assets/104819764/d59fb469-b3c0-4368-abe5-8186bbfc3245)

여기에서만 문제가 조금 있는 것 같고, 다른 곳엔 이상 없는 것 같습니다!
수고하셨습니다!

2024-07-05 08:43 UTC, JYeyun approved these changes

2024-07-05 09:09 UTC, merged