산책 화면 현재 위치 트래킹 해제 이후, 특정 조건(시간?) 달성 시 다시 트래킹하도록 처리: 김찬교
nbc-final-team2/ddaraogae pull request #258
Opened 2024-06-30 08:55 UTC by theBettor

resolved: #220 

1. timer 사용해서 tracking을 다시 잡습니다(트래킹 모드는 두 곳에서 선언됩니다.)
2. minZoom, maxZoom으로 볼 수 있는 곳을 제한했습니다.
3. 원래 줌 확대 및 축소했을때 location overlay가 사라지는 문제가 있었는데 해결했습니다.

2024-07-01 01:50 UTC, winteryy requested changes
코드 상에서 보이는 부분들 피드백 드렸습니다!

2024-07-01 01:50 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
> +    val scope = CoroutineScope(Dispatchers.Main) // UI 스레드에서 실행될 코루틴 스코프
public 프로퍼티인 이유와 UI 스레드에서 동작해야 하는 이유가 있나요??

2024-07-01 01:50 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
> +    private var trackingModeJob: Job? = null
`onViewDestroyed()` 시점에 해당 job이 존재한다면 cancel 후에 null처리 했으면 좋겠습니다

2024-07-01 02:13 UTC, theBettor commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
> +    val scope = CoroutineScope(Dispatchers.Main) // UI 스레드에서 실행될 코루틴 스코프
scope 변수는 잘못 위치한것 같아서 수정했고, 지도 객체도 ui스레드에서 동작해야되는걸로 알고 있고, Dispatchers.Main 말고는 더 아는게 없긴한데 다른 방법이 있을까요?

2024-07-01 08:58 UTC, theBettor commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/walk/WalkFragment.kt
> +    private var trackingModeJob: Job? = null
해당 부분 onDestoryView될때가 아니라 onStop 될때 cancel하는 것으로 정리했습니다!

2024-07-02 01:16 UTC, winteryy approved these changes

2024-07-02 01:17 UTC, neoneoneo123 approved these changes
확인했습니다.

2024-07-02 01:31 UTC, merged