산책 도장 리스트 개선및 프로그래스바 게이지 초기화 시점 변경
nbc-final-team2/ddaraogae pull request #259
Opened 2024-07-01 07:21 UTC by juseonghyun

- 산책 도장 리스트 개선
- 프로그래스바 게이지 초기화 시점을 최근 1주일이 아닌 월요일 기준으로 변경
## 참고사항
commit issue number를 잘 못 표기한게 있습니다. 유의바랍니다!!

resolved: #242

2024-07-01 10:16 UTC, neoneoneo123 requested changes
성현님, 고생 많으셨습니다!

스탬프 상세 내용을 확인할 수 있어서 좋은 것 같아요.

2가지 정도의 코멘트가 있어서 남겨드립니다!

2024-07-01 10:16 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampAdapter.kt
>              }
저는 DiffUtil에서 areItemsTheSame 함수 안에서는 아이템들의 **고유값**을 비교하는 것으로 이해하고 있습니다.
(https://jermainedilao.medium.com/demystifying-diffutil-itemcallback-class-8c0201cc69b1)

사용하시는 stampModel의 num 값의 역할이 고유값의 역할을 하는 걸까요?
id에서 num으로 변경하신 이유가 무엇인지 궁금하네요!

2024-07-01 10:16 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampFragment.kt
> +class AllStampFragment : Fragment() {
<img width="840" alt="image" src="https://github.com/nbc-final-team2/ddaraogae/assets/128209823/5ff0512b-6c6c-48b1-97af-2a4ccea750e9">

화면을 회전하면 리스트의 아이템들이 좌측으로 몰려보이는 현상이 있습니다!

2024-07-01 12:50 UTC, IamJuco commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampAdapter.kt
>              }
네! 처음 AllStampAdapter를 구성할때는 그저 사용자가 얻은 산책 도장의 총 갯수를 가져오는 화면을 구성 하였었는데요.
 당시에는 GetStampListByPeriodUseCase를 이용하였는데 이 usecase는 StampEntity를 return해주고 있었습니다.

    @Parcelize
    data class StampEntity(
        val id: String?,
        val stampNum: Int?,
        val getDateTime: Date?,
        val name: String?,
    ) : Parcelable
그래서 id 값을 비교해주고 있었는데,

산책 리스트 화면을 개선하면서 GetStampListByPeriodUseCase에서 GetStampInfoListUseCase를 사용하게 되었는데
해당 유스케이스의 return값은 StampInfoEntity로 변수 num이 고유 id 값을 대신 하고 있었습니다.
        
    data class StampInfoEntity(
        val num: Int,
        val title: String,
        val description: String
    )

종합하면 사용하는 usecase를 바꾸게 되었는데 바꾼 usecase에서 return값의 고유값의 명칭이 id에서 num으로 변경되어 바꾸게 되었습니다.

[app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/StampInfo.kt](url)
위 링크 보시면 이해가 잘 되실겁니다!

2024-07-01 12:52 UTC, IamJuco commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampFragment.kt
> +class AllStampFragment : Fragment() {
해당 내용 확인하고 수정 하였습니다.
item에서 부모 컨테이너를 wrap_content로 했더니 문제가 발생하였네용
match_parent로 변경하면서 해결하였습니다!
[e3a6a09b332d9fcb572396b06479014f0a2e70db](url)

추가로 Click하면 넘어가는 화면에서도 가로모드 방어를 위해 NestedScrollView를 추가하였습니다!
[4c4c38ae6ca08c73c1025f21c431a1f1ad20e2f6](url)

2024-07-02 01:26 UTC, theBettor approved these changes
지연님 피드백으로 개선하신 부분까지 확인했습니다 고생하셨어요!

2024-07-02 01:33 UTC, winteryy requested changes
나머지는 어제 zep에서 말씀드렸던 부분이라 고쳐진 것 같습니다
몇 부분만 확인 부탁드립니다!

2024-07-02 01:33 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/StampDetailViewModel.kt
> +    val stampList: LiveData<List<StampModel>> = _stampList
StateFlow로 리팩터링 가능하신가요?

2024-07-02 01:33 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/StampDetailFragment.kt
> +    }
어제 언급했던 부분인데 아직 안 고쳐진 것 같습니당

2024-07-02 01:33 UTC, winteryy commented on app/src/main/res/layout/fragment_stamp_detail.xml
> +        android:layout_height="match_parent"
ConstraintLayout 내부 요소인데 match_parent로 되어 있네용

2024-07-02 01:44 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/AllStampAdapter.kt
>              }
아 명칭이 바뀐걸로 이해하면 되는거군요. 알겠습니다!

2024-07-02 02:20 UTC, IamJuco commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/StampDetailFragment.kt
> +    }
확인했고 수정했습니다~

04e96983b562e8a668dff45d61ebefaba5e6667a

2024-07-02 02:20 UTC, IamJuco commented on app/src/main/res/layout/fragment_stamp_detail.xml
> +        android:layout_height="match_parent"
확인했고 수정했습니다~

e1840cb7ba142afee5765f9cb8e4895ef91eecc4

2024-07-02 02:21 UTC, IamJuco commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/stamp/StampDetailViewModel.kt
> +    val stampList: LiveData<List<StampModel>> = _stampList
네! 한번 시도해 보았습니다.

93e4b7108171fe1648d4ce48d9e342f553e4ec4c

2024-07-02 05:25 UTC, neoneoneo123 approved these changes

2024-07-02 09:56 UTC, winteryy approved these changes
고생 많으셨습니다👍👍

2024-07-03 01:07 UTC, merged