잔존 데이터 예외처리 완료
nbc-final-team2/ddaraogae pull request #271
Opened 2024-07-01 14:29 UTC by IamJuco

resolved: #270 
resolved: #235

2024-07-02 00:43 UTC, JYeyun approved these changes
확인했습니다.

2024-07-02 09:49 UTC, theBettor approved these changes
확인 했습니다! 요청이 있는데 따로 방문하겠습니다!

2024-07-02 10:02 UTC, winteryy approved these changes

2024-07-03 01:25 UTC, theBettor requested changes
1.
![스크린샷 2024-07-03 오전 10 25 36](https://github.com/nbc-final-team2/ddaraogae/assets/89888486/55e9da28-1d4e-4d8d-9c42-8ac203be8a8d)
이거를 추가하셔서 dogInfo가 null일때 tvBeforetime.text를 add dog로 변경해주세요.

2. tvBeforetime 변수명을 tvBeforeTime으로 id값이랑 같이 바꿔주세요,

2024-07-03 01:33 UTC, theBettor approved these changes
최곱니다 감사해용!

2024-07-03 02:05 UTC, neoneoneo123 approved these changes
확인했습니다.

2024-07-03 02:18 UTC, merged