[refactor] 회원 탈퇴 로직 변경
nbc-final-team2/ddaraogae pull request #277
Opened 2024-07-02 04:31 UTC by JYeyun

- 로그인 시 인증 다이얼로그에서 회원탈퇴 리팩토링
- 마이페이지 viewModel, fragment 수정
- 마이페이지 회원탈퇴 버튼 클릭 시 회원가입 제공업체를 파악하고 해당 방식으로 재인증 하도록 수정

#256

2024-07-02 06:00 UTC, neoneoneo123 commented
로그인하고 1시간 지난 후에 탈퇴하려고 하면, 재인증이 필요해서 여태 탈퇴가 잘 안되었던거 맞죠?

로그인 켜놓고 1시간 기다렸다가 테스트를 해야하겠네요 ㅋㅋㅋㅋ

2024-07-02 07:00 UTC, neoneoneo123 requested changes
앱 실행 -> 구글 회원가입 -> 로그인 -> 1시간 방치 -> 회원탈퇴

이렇게 하면
- 비밀번호를 입력하라고 합니다. 아무 텍스트나 눌러서 진행하면,
- 회원탈퇴에 실패했습니다. 토스트가 뜹니다.
- firebase 상에서는 해당 유저에 대한 일부 데이터만 날라갑니다.

2024-07-02 07:01 UTC, IamJuco approved these changes
테스트상 회원탈퇴가 잘되었습니다!
수고하셨습니다.

2024-07-02 10:03 UTC, winteryy requested changes
문제가 있던 부분 모두 고치면 re request 요청해주세요!
아직 브랜에 await() 붙이는게 반영이 안 된 것 같습니당

2024-07-02 12:10 UTC, winteryy approved these changes
항상 파이어베이스가 말썽이네요
고생 많으셨습니다👍

2024-07-04 03:45 UTC, neoneoneo123 approved these changes

2024-07-04 07:13 UTC, merged