home의 State들을 하나의 dataclass로 통합
nbc-final-team2/ddaraogae pull request #279
Opened 2024-07-02 05:29 UTC by IamJuco

- HomeUiState 안에서도 더 쪼개려고 했지만 생각보다 state수가 적어 쪼개지 않았습니다.

resolved: #272

2024-07-03 09:09 UTC, winteryy requested changes
수정할 부분이 보여서 코멘트 드렸습니다!

2024-07-03 09:09 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
>                  }
UiState를 collect 하는 코드를 하나로 통합해주세요!

2024-07-03 09:09 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
> +                    dogList = dogList,
기존에 있던 dogList에 대한 로직 누락 시키면 안됩니다. 여러 마리의 반려견이 있을 때 선택된 반려견을 지우고 홈 화면에 다시 돌아갔을 때, 반려견 리스트 내의 0번째 반려견에 대한 선택처리가 이뤄지지 않기 때문입니다.

2024-07-03 13:37 UTC, IamJuco commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
> +                    dogList = dogList,
앗 실수 했습니다. 잡아주셔서 감사합니다! 해결했습니다.

fd5effed3d039f7a8336f6014f43967c1dd0554c

2024-07-03 13:37 UTC, IamJuco commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeFragment.kt
>                  }
확인했습니다!

fd5effed3d039f7a8336f6014f43967c1dd0554c

2024-07-04 02:45 UTC, theBettor reviewed
이거 작업이 다 끝난건가용?

2024-07-04 03:11 UTC, IamJuco commented
@theBettor 네 끝났습니다

2024-07-04 03:44 UTC, theBettor approved these changes
고생하셨습니다!

2024-07-04 03:55 UTC, winteryy requested changes
ViewModel 내 코드만 다시 수정하면 될 것 같습니다.
그리고 아마 develop 브랜치 pull 받으시면, 제가 코루틴 lifecycle 다시 viewLifecycle로 바꿔둔 것 때문에 conflict 날 거 같은데, 혹시나 새로 코루틴 적용하신 부분은 전부 viewLifecycleOwner.lifecycleScope 사용하시면 됩니다

2024-07-04 03:55 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
> +                    dogList = dogList.apply { if (this.isNotEmpty()) this[0].isSelected = true },
이거 dogList에 
```
selectedDogInd?.let {
                    dogList
                } ?: dogList.apply { if (this.isNotEmpty()) this[0].isSelected = true }
```

기존에 있던 이 코드 모두가 들어가야 합니다

2024-07-04 07:54 UTC, IamJuco commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/HomeViewModel.kt
> +                    dogList = dogList.apply { if (this.isNotEmpty()) this[0].isSelected = true },
기존에 누락된코드 해결했습니다.
3669eacf51e9ddc94f6c270beda37047f322e466

conflict 날 수 있는 문제 해결했습니다.
76905c0a3c5c3c9182f358748c3721bd1bf9d196

2024-07-04 09:26 UTC, winteryy approved these changes
고생 많으셨습니다👍

2024-07-04 09:33 UTC, merged