[bug]반려견 페이지 back 오류 수정
nbc-final-team2/ddaraogae pull request #301
Opened 2024-07-04 14:13 UTC by JYeyun

#281 
반려견 삭제 후 돌아왔을때 detail fragment -> list Fragment로 넘어가는 시간이 오래 걸립니다.
그 동안 로딩 창을 띄우거나 다른 방법을 통해 이를 보완하고 싶은데 방법이 생각이 안나서 아이디어 있으신 분 말씀 주시면 감사하겠습니다 ㅠ
로딩창 띄우는 건 viewModel에서 시도해 봤는데 오래걸리는게 fragment에서 걸리는 것 같아서 별 효과를 못봤습니다. fragment에서 넘어갈때까지 로딩창 띄우는 방법이 있을까요?

https://github.com/nbc-final-team2/ddaraogae/assets/117142316/12739814-5ee1-47a9-8c85-0e3d52933097

2024-07-04 15:34 UTC, JYeyun commented
해당 문제 해결 했습니다!

2024-07-05 02:08 UTC, winteryy approved these changes
코멘트 드린 한 부분만 고쳐서 merge하면 될 것 같습니다
나머지 부분은 어제 말씀드렸던 대로 잘 변경된 것 같습니다

2024-07-05 02:08 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/dog/DetailPetFragment.kt
>                  .commit()
여기도 popBackStack()으로 변경되어야 할 것 같습니다!

2024-07-05 02:22 UTC, theBettor requested changes
parentFragmentManager.popBackStack()을 사용하셔서 잘 해결된 것으로 보입니다! 고생하셨습니다!
다만 
[Screen_recording_20240705_112001.webm](https://github.com/nbc-final-team2/ddaraogae/assets/89888486/cba8ecac-4269-4fd0-8132-4ccca37a14c7)
중간중간 아주 빠르게 loading dialog가 보이는 것 같은데 저렇게 아주 빠르게 보여줄거면 안보여주는게 더 나은 방법이 아닐까? 생각해 봤습니다.

2024-07-05 04:09 UTC, neoneoneo123 approved these changes
확인했습니다.

2024-07-05 04:55 UTC, theBettor approved these changes
일단 문제는 없으니 approve로 바꿉니다

2024-07-05 07:21 UTC, merged