구글 버튼 수정, mypage 피드백 수정
nbc-final-team2/ddaraogae pull request #314
Opened 2024-07-16 05:59 UTC by JYeyun

- 구글 로그인 버튼 수정 : 글자 중앙 정렬
- mypage 알림 설정 문구 수정
- mypage 글자 다크테마 대응되게 수정

2024-07-16 06:48 UTC, neoneoneo123 approved these changes

2024-07-17 06:59 UTC, winteryy requested changes
그 때 디자인 튜터님이 말씀하신 것처럼
마이페이지의 메뉴 순서 변경 및 < 아이콘 설정도 적용되면 좋을 것 같습니다

2024-07-19 07:43 UTC, JYeyun commented
희광님 말씀 주신 부분은 밑에 pr에 작업해서 올렸습니다
https://github.com/nbc-final-team2/ddaraogae/pull/310

2024-07-19 09:22 UTC, winteryy approved these changes
확인했습니다

2024-07-20 23:31 UTC, merged