[Feat] 반려견 상세페이지, 수정페이지, 추가페이지
nbc-final-team2/ddaraogae pull request #39
Opened 2024-06-05 11:38 UTC by JYeyun

- 반려견 정보 추가
- 반려견 상세 정보
- 반려견 수정

2024-06-05 14:48 UTC, winteryy requested changes
몇 부분 코멘트 드렸습니다
고생 많으셨습니다!

2024-06-05 14:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +            }
null-safe의 목적으로 구현했다면, `Glide` 코드 구현 부분에서 `imageUri`가 아닌 `it`을 통해 접근하면 더 좋을 것 같습니다

2024-06-05 14:48 UTC, winteryy commented on app/src/main/AndroidManifest.xml
>                  <action android:name="android.intent.action.MAIN" />
이건 테스트 용도로 변경하신건가요? `MainActivity`가 manifest 내에서 소실된 상태로 보입니다

2024-06-05 14:48 UTC, winteryy commented on app/src/main/res/layout/activity_edit_pet.xml
>                  android:layout_width="match_parent"
반려견 정보를 수정하는 부분이 새로운 Activity로 구현되었다면
아래 표시한 부분에 백 버튼을 구현해서 직관적인 UI/UX를 제공할 수 있을 것 같습니다.

![image](https://github.com/nbc-final-team2/ddaraogae/assets/104819764/a1e80d38-9146-4210-8528-09f217b61eb9)

2024-06-05 14:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +                    dogDataList = state.listPet
`flowWithLifecycle()` 빼먹기 쉬운 부분인데 신경써주셨네요👍

2024-06-05 14:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +        }
조금 더 ViewModel을 활용하는 형태로 변경해볼 수 있을 것 같습니다.
현재 ViewModel을 adapter에 들어갈 반려견 리스트를 collect 하는 용도로만 이용하고 있습니다.
UI 단에서 일어난 이벤트를 바탕으로 ViewModel 내에서 선택된 반려견 정보 또한 UiState로 나타내 줄 수 있고,
이를 collect해서 ViewModel의 데이터를 기반으로 선택된 반려견 정보를 UI에 바인딩 할 수 있을 것 같습니다!

2024-06-05 14:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetAdapter.kt
> +class DetailPetAdapter(val context: Context) : RecyclerView.Adapter<DetailPetAdapter.ItemViewHolder>() {
나중에 ListAdapter와 DiffUtil을 활용하는 형태로 리팩터링 하는 것도 좋을 것 같습니다.
수정된 반려견 정보에 의해 데이터셋 변경이 잦을 수 있는데, 변경된 부분만 감지해서 변경 처리해야 하는 번거로운 부분을 손쉽게 구현할 수 있습니다!

2024-06-05 14:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetViewModel.kt
> +    val uiState:StateFlow<DetailUiState> = _uiState.asStateFlow()
👍👍

2024-06-05 14:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DogModel.kt
> +) : Serializable
`Parcelable`이 아닌 `Serializable`을 택하신 이유가 궁금합니다!
또 필수 정보들도 nullable한 프로퍼티로 설정하신 이유도 궁금합니다

2024-06-05 14:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +    }
`DetailPetActivity`에서 선택한 반려견 데이터가 노출되지 않는 것 같은데, 아직 구현되지 않은 부분일까요?


https://github.com/nbc-final-team2/ddaraogae/assets/104819764/88f71661-9047-4dac-a428-534f77dd3640

2024-06-05 14:48 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +    }
이 부분은 어떤 코드인지 궁금합니다!

2024-06-07 03:48 UTC, neoneoneo123 requested changes

2024-06-07 03:48 UTC, neoneoneo123 commented on app/src/main/AndroidManifest.xml
> -            android:name=".presentation.ui.main.MainActivity"
manifest에 main activity가 없어졌습니다..!

2024-06-07 03:48 UTC, neoneoneo123 commented on app/src/main/res/layout/activity_edit_pet.xml
>                  android:layout_width="match_parent"
저도 동일 의견 드립니다!

2024-06-07 03:48 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +        dogData = intent.getSerializableExtra("dogData") as DogModel
음.. EditPetActivity에서 dogData로 get하려고 했으나, 정상적으로 화면에 보여지지 않고 있습니다..!

![image](https://github.com/nbc-final-team2/ddaraogae/assets/128209823/f6922ab6-41dd-44c2-b815-6b009f613a8c)

제 PC에서는 이렇게 보입니다..!

2024-06-07 03:48 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +        if (buildName.equals("Xiaomi")) {
잘 몰라서 여쭙는 부분입니다만,
buildName에 대해서 Xiaomi인 경우에 대해서만 uri.path!!를 return하는 이유가 무엇인가용?

2024-06-07 04:14 UTC, closed without merging

2024-06-09 17:27 UTC, JYeyun commented on app/src/main/AndroidManifest.xml
>                  <action android:name="android.intent.action.MAIN" />
테스트 용으로 작성하고 빼고 올린다는게 그냥 올린 것 같습니다. 다시 수정하겠습니다.

2024-06-09 17:28 UTC, JYeyun commented on app/src/main/AndroidManifest.xml
> -            android:name=".presentation.ui.main.MainActivity"
테스트 용으로 작성하고 빼고 올린다는게 그냥 올린 것 같습니다. 다시 수정하겠습니다.

2024-06-09 17:29 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +        if (buildName.equals("Xiaomi")) {
저 함수가 이미지를 갤러리에서 가져왔을때 Uri를 기반으로 파일 위치를 찾아 File형태로 변환하는 함수인데 샤오미사 핸드폰은 갤러리에서 이미지를 가져올때 file형태로 넘어와 변환할 필요가 없다고 합니다.

2024-06-09 17:37 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +            if(etName.text!!.isEmpty()) Toast.makeText(this@AddActivity, "이름은 필수 작성 항목입니다!", Toast.LENGTH_SHORT).show()
확인했습니다