spot을 위한 검색 api 구현
nbc-final-team2/ddaraogae pull request #48
Opened 2024-06-07 12:44 UTC by neoneoneo123

resolved: #43

---

2024-06-07 13:35 UTC, winteryy approved these changes
전반적으로 깔끔하게 구현된 것 같습니다!
Hilt랑 클린 아키텍처에 금방 능숙해지시네요

2024-06-07 13:35 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/NetworkModule.kt
> +    annotation class KakaoInterceptorOkHttpClient
Retention 이용해서 같은 클래스를 다르게 주입하는 코드가 잘 작성된 것 같습니다!👍

2024-06-07 13:35 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/app/di/NetworkModule.kt
> +    }
`Retrofit.Builder()` 공통 코드 빼내서 재활용한 것도 인상적이네요!

2024-06-09 17:42 UTC, juseonghyun requested changes

2024-06-10 01:47 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/StoreDto.kt
> +    @SerializedName("category_group_name") val category_group_name: String?,
수정했습니다!

https://github.com/nbc-final-team2/ddaraogae/pull/48/commits/41e02cd9ed26d1453cdd031f418f2d876f0ba6d8

2024-06-10 04:03 UTC, juseonghyun approved these changes
변경 사항 확인했습니다 수고하셨습니다!

2024-06-10 04:10 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StoreRepositoryImpl.kt
> +}
![image](https://github.com/nbc-final-team2/ddaraogae/assets/128209823/d2bf2ccb-12d6-46b6-b6d2-802c87815410)

2024-06-10 08:26 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StoreRepositoryImpl.kt
> +}
동물병원, 애견동반 쿼리로 요청하는 부분을 2개로 나누었습니다.
- StoreRepository에서 2개의 함수 사용
  - 각 함수에 대해 usecase를 사용하도록 추가 및 수정

2024-06-10 08:43 UTC, winteryy approved these changes
고생하셨습니다

2024-06-11 01:09 UTC, merged