[Feat] google 로그인
nbc-final-team2/ddaraogae pull request #49
Opened 2024-06-07 12:56 UTC by JYeyun

- google 로그인 구현

#46

2024-06-08 11:12 UTC, winteryy requested changes
이메일 로그인 구현하시면서 함께 리팩터링하면 좋을 부분들 코멘트 남겼습니다
고생하셨습니다!

2024-06-08 11:12 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
> +        }
해당 state는 이미 관찰되고 있습니다
state 내에서 user 로그인 상태와 구글 로그인 성공 여부를 따로 고려하고 있어서 생기는 로직 형태인 것 같습니다
state에선 로그인 여부만 나타내고 구글 로그인 성공 후, 현재 유저 값을 체크해 로그인 여부 값을 업데이트 해주는 형태로 사용하거나, 아니면 차라리 SharedFlow를 이용해서 유저 정보를 성공적으로 불러왔음을 이벤트로 나타내주는 것도 좋을 것 같습니다

2024-06-08 11:12 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
> +        googleSignInClient = GoogleSignIn.getClient(this, gso)
gso가 스코프 내에서 변경되지 않으므로 val로 선언해주면 좋겠네용

2024-06-08 11:12 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
> +    }
위에서 언급한 내용들을 수정하면 로그인 유저 확인 이벤트 발생 혹은 로그인 성공 여부 상태 관찰만을 통해서 MainActivity로 연결해주는 코드만 남길 수 있을 것 같습니다!

2024-06-08 11:12 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
> +) : ViewModel() {
Hilt 활용 잘 하신 것 같습니다!

2024-06-08 11:12 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
> +    val uiState: StateFlow<LoginUiState> = _uiState.asStateFlow()
Flow가 낯설 수도 있을텐데 기본적인 형태를 잘 알고 계신 것 같습니다

2024-06-08 11:12 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
> +        }
현재 유저 정보를 가져와서 null인지 확인한 statement 자체를 바로 flow에 업데이트 해줄 수 있을 것 같습니다
그리고 현재 코드에서 `currentUser`에 null-safe 체크는 불필요해보입니다
uiState를 활용할 때, 불변형 데이터를 유지한 채 `copy()` 해서 사용하신 부분은 너무 좋습니다!

2024-06-08 11:12 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
> +    }
여기도 `successSignInGoogle`에 대한 null-safe 체크는 불필요해보이네용

2024-06-09 17:23 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
> +    }
onActivityResult() -> registerForActivityResult() 제외 피드백 주신 점 수정완료했습니다.
c7d55652ae8f97bcdba31f7e731bc2f8ce0a9c97

2024-06-09 17:24 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
> +        }
onActivityResult() -> registerForActivityResult() 제외 피드백 주신 점 수정완료했습니다.
https://github.com/nbc-final-team2/ddaraogae/commit/c7d55652ae8f97bcdba31f7e731bc2f8ce0a9c97

2024-06-10 02:02 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
> +    }
dda28ea9fe1d90f6c755129e3f563a7e50d6af60

2024-06-10 09:04 UTC, neoneoneo123 commented on app/src/main/res/values/strings.xml
> +    <string name="default_web_id">849448350578-obmt630heqpkg7pummgc6agrmlgs4ffa.apps.googleusercontent.com</string>
여기서 사용한 name이 LoginActivity에서 사용하는 name(default_web_client_id)과 달라서 리뷰할 때에는 임의로 LoginActivity에서 사용하는 name을 default_web_id으로 변경하여 사용하였습니다. 참고 바랍니다!

2024-06-10 09:07 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
> +                )
89cdc0de6d85115084c44eca08f7db2edbb2b7f0

말씀 주신 부분 확인 후 수정했습니다!

2024-06-10 09:09 UTC, JYeyun commented on app/src/main/res/values/strings.xml
> +    <string name="default_web_id">849448350578-obmt630heqpkg7pummgc6agrmlgs4ffa.apps.googleusercontent.com</string>
R.string.default_web_client_id가 json파일 안에 있는 string이라 해당 이름으로 사용해도 잘 돌아갈겁니다! string 파일 안에 있는 default_web_id는 삭제하겠습니다.

https://github.com/nbc-final-team2/ddaraogae/commit/89cdc0de6d85115084c44eca08f7db2edbb2b7f0

2024-06-10 09:15 UTC, winteryy requested changes
고생하셨습니다 몇 군데만 확인 부탁드립니다!

2024-06-10 09:15 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
> +        }
여기서 let 문은 왜 쓰셨나요?

2024-06-10 09:17 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginViewModel.kt
> +        }
해당 부분에서 successToken 값을 넘겨야 하는데 실수로 successSignInGoogle 값을 넘긴 것 같습니다. 지연님 피드백 받고 수정했습니다.

https://github.com/nbc-final-team2/ddaraogae/commit/89cdc0de6d85115084c44eca08f7db2edbb2b7f0

2024-06-10 09:23 UTC, neoneoneo123 approved these changes

2024-06-10 09:29 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginUiState.kt
> +}
넵 확인했습니다.
6fcbd8b098a1ec8a45686cdf80dbb112dff16ed8

2024-06-10 09:29 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/login/LoginActivity.kt
> +            }
초기화 위치 변경했습니다!
6fcbd8b098a1ec8a45686cdf80dbb112dff16ed8

2024-06-10 11:52 UTC, merged