날씨 ui 상에 지역을 표시할 수 있도록 좌표-주소 변환 api 구현
nbc-final-team2/ddaraogae pull request #51
Opened 2024-06-07 13:46 UTC by neoneoneo123

resolved: #50

---

사용법은 기존 날씨 usecase 사용법과 동일합니다.

--

![image](https://github.com/nbc-final-team2/ddaraogae/assets/128209823/eacaf206-7773-4c95-b4c1-1815facf817b)

entity 상에 지역이 포함되었습니다.

2024-06-08 12:47 UTC, winteryy requested changes
제가 null 처리 정책을 명확하게 하지 않아서, 불명확해진 부분들이 조금 보입니다
월요일에 응답 null 처리 프로세스를 함께 논의했으면 좋겠습니다
null 처리 외 흐름은 큰 문제는 없는 것 같습니다, 고생 많으셨습니다!👍

2024-06-08 12:47 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
> +    @SerializedName("y") val y: Double,
`Address` 응답의 프로퍼티들이 nullable이 아니라고 확신할 수 있는 근거가 있나요?

2024-06-08 12:47 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/StoreMapper.kt
> +        val combinedList = (resultForHospital + resultForFood).distinctBy { it.id }
`distinctBy()`를 쓰니 한결 간결하네요!

2024-06-08 12:47 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        if (addressData == null) { addressData = address.documents?.get(1) }
이건 어떤 로직인가요? `address` 데이터가 null이려면 `address`의 `documents`가 null인 상황인데, `address.documents`의 인덱스 1번째 데이터를 가져오려고 시도하고 있습니다
만약 `documents`의 원소로 null을 받을 수 있는 경우라서 이렇게 구성했다면, 아래의 `get()` 요청은 `documents`가 null이 아니고 1번째(인덱스 기준) 원소가 null일 때 Excecption을 발생시킬 것 같습니다

2024-06-08 12:47 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        val cityData = addressData?.region_3depth_name ?: addressData?.region_2depth_name ?: addressData?.region_1depth_name ?: ""
여기도 마찬가지로 `addressData`가 null인 상황에서 엘비스 연산자가 유효해지는데, `addressData`가 null이라면 다른 프로퍼티들도 존재하지 않으므로 불필요한 동작이 될 것 같습니다

2024-06-08 12:47 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StoreRepositoryImpl.kt
> +        return storeItemList
모종의 이유로 둘 중 하나의 요청에서만 exception이 발생했을 때도 해당 메소드는 죽게될 것 같습니다
의도된 동작인가요??

2024-06-09 17:29 UTC, juseonghyun requested changes

2024-06-09 17:29 UTC, juseonghyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
> +data class City(
data class 이름과 코틀린파일 이름과 일치 하지 않습니다 확인부탁드립니다!

data class는 이름이 City이고 코틀린파일 이름은 CityDto입니다!

2024-06-09 17:29 UTC, juseonghyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/StoreDto.kt
> +    @SerializedName("category_name") val category_name: String,
변수명은 카멜케이스로 작성 하셔야할것 같습니다!

2024-06-10 01:56 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
> +    @SerializedName("y") val y: Double,
nullable로 변경하겠습니다.

2024-06-10 01:56 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/StoreMapper.kt
> +        val combinedList = (resultForHospital + resultForFood).distinctBy { it.id }
추천해주셔서 사용해봤습니다! 감사합니다~

2024-06-10 01:57 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        if (addressData == null) { addressData = address.documents?.get(1) }
![image](https://github.com/nbc-final-team2/ddaraogae/assets/128209823/b85f7cfd-6bde-4f5c-821a-5372a0b50470)

응답이 이런식으로 오고 있습니다.
B타입이 혹시 null로 오게 되면 H 타입이라도 가져다 쓰게끔 하고자 의도한 코드입니다.

2024-06-10 01:59 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        val cityData = addressData?.region_3depth_name ?: addressData?.region_2depth_name ?: addressData?.region_1depth_name ?: ""
엇, 네네 addressData가 null이면 불필요한 동작이 되겠네요. 수정하겠습니다.

2024-06-10 02:02 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StoreRepositoryImpl.kt
> +        return storeItemList
음.. 의도하지 않았습니다. 해당 부분 수정해둘게요.

2024-06-10 02:05 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
> +data class City(
수정 했습니다.

2024-06-10 02:06 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
> +data class City(
https://github.com/nbc-final-team2/ddaraogae/pull/51/commits/f6a7e3981fc62efa95f909648809b0f58c18cf6c

커밋 링크입니다!

2024-06-10 02:10 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
> +    @SerializedName("y") val y: Double,
https://github.com/nbc-final-team2/ddaraogae/pull/51/commits/db1260f7f5e0f54a54b721c72741b6aa4e7a4ebb

2024-06-10 03:55 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
> +    @SerializedName("y") val y: Double,
튜터님과 논의 이후에 결정된대로 모든 변수를 nullable 하지 않도록 수정해두었습니다!

https://github.com/nbc-final-team2/ddaraogae/pull/51/commits/64fdfcfca331f2e2623c9b2d764d5de894114d78

2024-06-10 04:04 UTC, juseonghyun approved these changes
변경 사항 확인했습니다 수고하셨습니다!

2024-06-10 04:10 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/repository/StoreRepositoryImpl.kt
> +        return storeItemList
그리고 이 코멘트는 search api 관련 사항이라, https://github.com/nbc-final-team2/ddaraogae/pull/48 PR에서 다루겠습니다.

2024-06-10 06:29 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        if (addressData == null) { addressData = address.documents?.get(1) }
말씀해 주신 내용을 수정하면서 재차 테스트를 해본결과, cityData에 OO구, OO군이 들어가는게 적절할 것 같아 region2depthName만이 사용되도록 코드를 수정하였습니다.

- 몇몇 주소를 테스트해보니 depth3의 값이 "태평로1" "명동" "진부면" "중곡2동" 등으로 응답이 되면서 깔끔하게 OO동 이런식으로 데이터를 받을 수 없더라구요. 특히 OO로 + 숫자 와 같은 형태로 오게 되면 text 길이가 길어서 ui 위치를 잡는 데에도 귀찮은 일이 생길 것 같아 OO구 형태의 데이터만 취하도록 했습니다!


https://github.com/nbc-final-team2/ddaraogae/pull/51/commits/576ac2c06787bbbb1824c466f08704aad3655789

2024-06-10 06:29 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        val cityData = addressData?.region_3depth_name ?: addressData?.region_2depth_name ?: addressData?.region_1depth_name ?: ""
위 코멘트에서 말씀드린대로 addressData를 처리하는 방식 자체를 변경하였습니다!

https://github.com/nbc-final-team2/ddaraogae/pull/51/commits/576ac2c06787bbbb1824c466f08704aad3655789

2024-06-10 08:33 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/CityDto.kt
> +    @SerializedName("y") val y: Double,
장세진튜터님과 논의 후 다시 모든 변수를 nullable 하게 변경했습니다.

https://github.com/nbc-final-team2/ddaraogae/pull/51/commits/f64f5f2186a52e6226ced71a2c3702954d88c413

2024-06-10 08:58 UTC, winteryy requested changes
몇 군데 nullable 처리가 안된 곳이 보이는데 의도가 있나요?

2024-06-10 08:58 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/StoreDto.kt
> +)
여긴 아직 nullable 처리가 되지 않은 것 같습니다

2024-06-10 08:58 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        }
현재 if문 블럭은 `documents`가 null이거나, `docments`의 `get(0)` 결과가 null이거나, `region2depthName`이 null 혹은 공백값일 경우 진입하게 됩니다. 
`documents` 결과가 null일경우, cityData에는 null을 넣어야 하니 이 부분은 이해가 가는데, `get(0)`이나 그 하위 결과가 존재하지 않을 때 cityData에 `address.documents?.get(0)?.region2depthName`을 대입하는 이유를 알려주실 수 있나요??

2024-06-10 08:58 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StoreEntity.kt
> +    val lng: String,
여기도 아직 nullable 처리가 되지 않았네용

2024-06-10 09:29 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/dto/StoreDto.kt
> +)
희광님, store 관련 변경 사항은 https://github.com/nbc-final-team2/ddaraogae/pull/48 이 PR에서 관리하도록 해당 브랜치에 작업해두었습니다!

2024-06-10 09:29 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/domain/entity/StoreEntity.kt
> +    val lng: String,
희광님, store 관련 변경 사항은 https://github.com/nbc-final-team2/ddaraogae/pull/48 이 PR에서 관리하도록 해당 브랜치에 작업해두었습니다!

2024-06-10 09:48 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        }
음...
.으로 타고 들어가는 부분이 여럿 있어서 제가 놓친 것 같습니다.

```kotlin
val cityData = address.documents?.let { docs ->
    if (docs.isNotEmpty() && docs[0].region2depthName.isNullOrEmpty()) {
        docs.getOrNull(1)?.region2depthName
    } else {
        docs.getOrNull(0)?.region2depthName
    }
}
```

이런식으로 코드를 수정하면,

address와 documents의 null 가능성을 모두 처리하고,
documents 리스트가 비어있지 않고 첫 번째 요소의 region2depthName이 null이거나 비어있는 경우에만 두 번째 요소의 region2depthName을 할당하도록 처리가 가능할 것 같습니다!

2024-06-10 09:49 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/mapper/WeatherMapper.kt
> +        }
https://github.com/nbc-final-team2/ddaraogae/pull/51/commits/bd15a0a918741ed17148d6bbb5e54fbcb5f7e487

2024-06-11 01:14 UTC, merged