[feature] 반려견 추가, 상세정보, 수정 페이지 완료
nbc-final-team2/ddaraogae pull request #67
Opened 2024-06-11 10:30 UTC by JYeyun

- 반려견 추가(AddActivity)
- 반려견 상세정보 (DetailPetActivity)
- 수정 페이지(EditPetActivity)

- firebase연결 완료
- 기존 feedback 반영
- 강아지 나이 null값 에러 해결

#24

2024-06-12 05:45 UTC, neoneoneo123 requested changes
고생 많으셨습니다!

몇가지 코멘트를 작성하였습니다!

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +        setContentView(view)
view를 선언하고 초기화하여 사용하는 곳이 setContenView만 있을 것이라면,
setContenView(binding.root) 이런식으로 작성하는 것은 어떨까요?

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +                Log.d("testDog", "$newDog")
test에 사용하신 log는 제거하는 것이 좋을 것 같습니다!

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +                val breed = etBreed.text.toString()
음 이건 xml에서 수정하면 좋을 것 같은데, 이번 PR에서는 xml 코드가 부분적으로 보일 수 밖에 없어서 여기에 코멘트드립니다.

이름, 견종 입력칸에서 엔터키를 누르면 행이 변경되고 있습니다. 나이와 똑같이 한줄로 입력되도록 수정이 되면 좋을 것 같습니다!

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/model/DogItemModel.kt
> +@Parcelize
![image](https://github.com/nbc-final-team2/ddaraogae/assets/128209823/b819f460-21b8-46a5-a7e4-48398c143735)

import kotlinx.android.parcel.Parcelize 대신에
import kotlinx.parcelize.Parcelize를 사용하는 것은 어떨까요?

[참고링크](https://stackoverflow.com/questions/64925126/how-to-use-parcelize-now-that-kotlin-android-extensions-is-being-deprecated)

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +                        Log.d("testDogDetail", "${state.listPet}")
test log 코드는 삭제하는 것이 좋을 것 같습니다.

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +                        Log.d("testDogDetailElse", "${state.listPet}")
test log 코드는 삭제하는 것이 좋을 것 같습니다.

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +    }
선택한 강아지 이미지의 테두리 색상 표시를 위해 civ_border_width 설정이 필요할 것 같습니다!

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +    }
음.. adapter 상에서 처리가 필요할 것 같네요..!

2024-06-12 05:45 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +        lifecycleScope.launch {
반려견 정보가 없을 때 전체 화면으로 표시되는 ConstraintLayout를 다시 그려주고 있습니다.
그래서 appBar 부분을 새롭게 그려주게끔 되어있어네요..!

새롭게 ConstraintLayout을 그리는 것보다는 기존에 작성해주신 appbar 영역은 그대로 두고, 그 아래 영역만 별도의 layout으로 잡아 중복되는 코드를 줄이는 방향을 제안드립니다!

그렇게 되면 onCreate에 있는 
```kotlin
binding.btBack.setOnClickListener { finish() }
binding.btEmptyBack.setOnClickListener { finish() }
```
이 부분도 하나의 back 버튼에 대해서만 처리해도 되는 구조가 될 것 같습니다!

2024-06-12 15:31 UTC, JYeyun commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +        lifecycleScope.launch {
34c4ab9b41b18b5573bd8b9a6b8c4207be5be698

말씀주신 부분 한번에 수정해서 올렸습니다. 감사합니다.

2024-06-13 05:49 UTC, neoneoneo123 approved these changes
확인했습니다. 고생 많으셨습니다.

코멘트 하나를 드리지만 마이너한 건으로 approve 하였습니다.
다시 review하지 않아도 될 것 같아서, 반영만 부탁드립니다.

2024-06-13 05:49 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +        setContentView(view)
이 부분도 별도의 view 변수를 선언하여 사용할 필요는 없어보입니다!

2024-06-13 08:29 UTC, winteryy requested changes
![image](https://github.com/nbc-final-team2/ddaraogae/assets/104819764/c0c08e67-a6b5-4a23-8fe3-87d787767289)

초기 화면에서 기본 선택된 반려견에 대해 선택 효과(테두리)가 보이지 않습니다.
반려견 이미지가 없을 때 사용할 디폴트 이미지도 필요할 것 같습니다(현재 반려견 이미지가 없는 경우 테두리도 정상적으로 노출되지 않습니다)
일단 시간이 없어 크리티컬한 부분만 찾아 수정 요청 드립니다

2024-06-13 08:29 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/home/AddActivity.kt
> +        var gender = 0
성별 선택을 위한 Ui State 정보가 local 스코프 내에서 선언되고 이용되고 있습니다.
ViewModel 내에서 관리되는 것이 이상적이고, 어렵다면 최소한 전역변수로 빼내어야 할 것 같습니다

2024-06-13 08:29 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetActivity.kt
> +        viewModel.getDogList()
둘 다, 각각의 코루틴 내에서 실행되는 비동기 동작입니다. `deleteDogData()`의 실행 종료 이후 `getDogList()`가 실행된다고 보장할 수 없습니다

2024-06-13 08:29 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/DetailPetAdapter.kt
> +            return oldItem == newItem
DogItemModel의 id값을 비교해서 두 객체가 같은 것을 레퍼런싱 하고 있음을 확인해야 할 것 같습니다

2024-06-13 08:29 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/presentation/ui/mypage/EditPetActivity.kt
> +        ivDogThumbnail.setOnClickListener {
여기도 위에서 언급했던 것과 같은 이슈가 있습니다

2024-06-13 13:53 UTC, merged