이미지 변환 로직 구현
nbc-final-team2/ddaraogae pull request #70
Opened 2024-06-11 12:01 UTC by neoneoneo123

resolved: #54 

---

새롭게 UseCase가 추가되지는 않아서 사용법에 영향을 주지는 않을 것 같습니다.

---
test 영상입니다.
(test시 사용한 activity, viewmodel 코드는 PR에 포함되어있지 않습니다.)

https://github.com/nbc-final-team2/ddaraogae/assets/128209823/40fe0b11-a01f-48cd-a6c9-30a778a4318c

2024-06-11 12:34 UTC, theBettor reviewed
파베 아직 안들어가봐서... 저는 나중에 ㅎㅎ 화이팅입니다

2024-06-11 13:05 UTC, winteryy requested changes
죄송합니다 제가 제일 중요한 부분을 언질을 안 드렸네요..
이미지 파일을 어떤 타입, 어떤 방식으로 받을지 서비스 측과 논의 후에 수정이 필요해보입니다.

2024-06-11 13:05 UTC, winteryy commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +    }
dogThumbnail을 결국 사용자가 제공하는 `thumbnailUrl` 값을 이용하고 있습니다!
저는 서비스 측에서 이미지를 `insertDog()` 시에 다른 nullable한 File 타입 파라미터로 함께 넘길 수 있도록 하고(변경 필요), 
해당 파라미터가 null이 아니라면 그 파일을 `Uri.fromFile()` 이후 `putFile()`해서 넘기는 형태로 생각했습니다.

서비스 측에서 어떤 것으로 넘길지 아직 합의가 되지 않았을 것 같은데, 적절하게 수정이 필요할 것 같습니다.

2024-06-12 01:00 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +    }
음.. 예윤님과 얘기했을 때, 기기에서 이미지를 가져올 때 Uri로 가져온다고 들었습니다.
다만, 최대한 기존 코드를 수정하지 않으려고 String으로 타입을 유지한채로 구현을 했네요.

Entity를 수정해도 괜찮다고 하면
- dogThumbnail의 타입을 Uri?로 바꾸고
- convertImageUrl에서 dogThumbnail가 null이 아닐 때 Uri.fromFile() 이후 putFile() 처리

이런식으로 수정하면 될까요?

2024-06-12 02:43 UTC, neoneoneo123 commented on app/src/main/java/com/nbcfinalteam2/ddaraogae/data/datasource/remote/firebase/FirebaseDataSourceImpl.kt
> +    }
희광님, 오전 스크럼에서 논의한대로 수정하였습니다.
- insert, update 시 uri를 파라미터로 받아와 처리
- uri가 null일 경우 url convert 작업하지 않음(기존에 들어온 DogDto를 insert, update 처리함)

https://github.com/nbc-final-team2/ddaraogae/pull/70/commits/243fbe37a258f5a664cdcb9691bcb61f3702496c

2024-06-12 04:31 UTC, winteryy approved these changes
고생하셨습니다

2024-06-12 15:35 UTC, JYeyun approved these changes
확인했습니다. 해당 서비스 부분도 수정해놓도록 하겠습니다.

2024-06-12 16:19 UTC, merged